services:
  db:
    image: postgres:17
    container_name: msa-aryan-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: msa-aryan
      POSTGRES_PASSWORD: localdbpassword
      POSTGRES_DB: msa-aryan
    ports:
      - "5432:5432"
    volumes:
      - msa-aryan-db-data:/var/lib/postgresql/data

volumes:
  msa-aryan-db-data: